sudo: required
services:
  - docker
dist: trusty
language: node_js
node_js:
  - "8"
notifications:
  email: false
script:
  - make build
  - make coverage
deploy:
  provider: script
  on:
    branch: master
  script: make deploy
