sudo: false
dist: trusty
language: java
jdk:
  # Install JDK8 for html5 validator.
  - oraclejdk8
env:
  - NODE_VERSION="6.11.2"
notifications:
  email: false
before_install:
  - nvm install $NODE_VERSION
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  # Disable the spinner; it looks bad on Travis.
  - npm config set spin false
  - npm install
  - pip install --user html5validator
  # Unclear why we have to install this separately, since it's in package.json,
  # but Travis fails without it.
  - npm install -g cssbeautify-cli
script:
  - ./build
  - cat coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: firebase
  token:
    secure: "sW8jrLD4FxUSVEPdCr2l2IWXNvL4rRyJdX1UvNF+lUqcWrerQPDJaVNXBMVWxtU5fKB9+2b7Gl4jnC4OjEtt8NkJeeBLh6+YZy/JW+mMkiFJVWWzx3DuJNJtBnoDJsyovADahVbZRxZPY4wGPsnmfY56wHmB061wy/h48ws1pE9jelZW0vzgqyabw3SNT+mK40wbJSHL1R3ik6DFON67ubuclOMdIw19q/Dyx1ItjioXYXJgC11F2c6Y2pU3sFBU/6xzLF/xevPS146hGriaDBuERl0OP6RfPMZx2N9ZVyVGIuiNicknEWM0WsHe7Ia53il7YbTnJXu+my4k1XFlN/0DxTlZkLb2dhh2n3dEHmUhcW0KxjOjx3ypcx0CevsJJgJ1EfZglHPr+MUM++SST0PkHStD0kbzv/ReKdbLFJRDeZirtM6txmx7aIrTf8av7jSHfItJ0C/9vK8+Xiea4uucSS8QDmR6qtq6xWkx2D1XT7mqjIZHcP0CIujMMb6H6Ga46FCFVMK7ycImjr3JkpBie8AwBr49upjhBnyaSiZvu9TZCJsOU4X1mmAfWC6BnXhllQcDXX/uJAsz173C0Mgvng+5NaYiG7YuxWX3Tj5aS6mVifqiFRzfZyflAP40js8tjKmuiFvdXw21nTdYktLilwgw3gqO5SAP3e6iQBc="
  skip_cleanup: true
