# sudo is required to use Docker services in Travis
sudo: required
services:
  - docker
dist: trusty
language: node_js
node_js:
  - "8"
notifications:
  email: false
script:
  - make build
  - make coverage
